### ISSUE TITLE
Creating a new logo

### ISSUE THREAD

**Issue by jbeguna04** [kapito/vibration-tester-android#6]
Hi good day, i would like to create a new logo in your aaplication so that the users will be more interested in your app. I am not saying that your current logo/icon is bad, but i would like to enhanced your logo. Hoping for your positive response!

**Comment by kapito** [comment]
I'd happily welcome a new logo, as long as it matches the minimalistic theme of the app. Or even if it doesn't, it would likely be an improvement over what I currently have... Looking forward to it :)

**Comment by jbeguna04** [comment]
Hi Good Day! Sorry for it took me so long to create my designs of logo for your application
I would like to present to you my designs. I created two designs Please let me know  if you any suggestions or wanting for a change
![capture](https://user-images.githubusercontent.com/35353768/37860690-ae2b3c70-2f65-11e8-97ca-32f38250a5b8.JPG)

Thank You for your time

**Comment by kapito** [comment]
These look really great! I'd love to make one of them the app icon (probably the second one). Small suggestion: could you make the green of the Android/Smartphone components use the colour #00d070 as this is the colour I've used in the app :)

Thanks for your work!

**Comment by jbeguna04** [comment]
Sure anything for you. Ill be posting the suggested app here . Thank you

**Comment by jbeguna04** [comment]
I would like you know that the files are already done and ready to be use. Thank You

**Comment by kapito** [comment]
These look amazing, thanks! If you could send me the files I'll change the logo in an update soon, or if you'd like to create a pull request that works too. (My favourite is the first one -- they all look great however!)

Also if you'd like I'll add credits for the logo in the app description -- what name should I use?

**Comment by jbeguna04** [comment]
Jibbie R. Eguna(jbeguna04), That would be fine ill make a pull request later thanks

**Comment by jbeguna04** [comment]
By the way, How can i make a pull request?

**Comment by jbeguna04** [comment]
Hi, Already created a pull request Thanks!
